return {
    ["catppuccin-frappe"]    = "Catppuccin Frappe",
    ["catppuccin-latte"]     = "Catppuccin Latte",
    ["catppuccin-macchiato"] = "Catppuccin Macchiato",
    ["catppuccin-mocha"]     = "Catppuccin Mocha",
    ["kanagawa-dragon"]      = "Kanagawa Dragon",
    ["kanagawa-lotus"]       = "Kanagawa Lotus",
    ["kanagawa-wave"]        = "Kanagawa Wave",
    ["rose-pine-dawn"]       = "rose-pine-dawn",
    ["rose-pine-main"]       = "rose-pine",
    ["rose-pine-moon"]       = "rose-pine-moon",
    ["tokyonight-day"]       = "Tokyo Night Day",
    ["tokyonight-moon"]      = "Tokyo Night Moon",
    ["tokyonight-night"]     = "Tokyo Night",
    ["tokyonight-storm"]     = "Tokyo Night Storm",
}
